defaults:
  - experiment_real_base
  - _self_

experiment:
  compat:
    garment_type: 'tshirt_short'
    machine:
      hybrid_drag:
        x_distance_ratio: 0.3333 # for short-sleeve
        y_distance_ratio: 0.3  # for short-sleeve
  runtime_training_config_override:
    virtual_datamodule:  # datamodule for virtual dataset used for self-supervised learning
      tag: 'short_action14_8pts_real-hybrid'  # for short-sleeve hybrid-training
    logger:
      experiment_name: Tshirt-short-action14-dataset-v6_real

logging:
  tag: tshirt-short-stage3_real