defaults:
  - ../base/inference@_here_
  - _self_

experiment:
  compat:
    debug: False
    calibration_path: /mnt/c/Users/xuehan/PycharmProjects/UniFolding/data/calibration/v10
    camera:
      vis: False
      virtual_camera_intrinsics_path: /mnt/c/Users/xuehan/PycharmProjects/UniFolding/data/calibration/v10/camera_intrinsic_scanner.json
    garment_type: 'tshirt_long'
    seed: 41234
    machine:
      x_lim_m: [0.15, 1.02]
      y_lim_m: [-0.78, 0.86]
      z_lim_m: [0.00, 0.3]
      safe_distance_m: 0.15
  environment:
    executable_file: '@editor'
#    executable_file: '/home/hanxue/UnityProjects/garmentimitationrfu/ClothDynamics.exe'
    port: 5004
    env_type: ClothDynamics
    camera_id: 221
    random_fold_type: 'tshirt_long'
    particle_scale: 100.0
    grasp_height_range: [0.5, 1.5]
    grasp_plane_x_offset_range: [-0.2, 0.2]
    grasp_plane_z_offset_range: [0.4, 0.6]
    stretch_z_offset: 0.4
    stretch_height: 0.8
    stretch_thr: 0.25
    stretch_max_distance: 1.2
    fling_end_offset: 0.35
    fling_end_height: 0.05
    fling_speed: 0.5
    fling_min_distance: 0.3
    pick_and_place_height: 0.2
    pick_and_place_speed: 0.1
    medium_gravity: 2.0
    high_gravity: 15.0
    down_speed: 0.4
    time_scale: 4.0
    debug: False
    seed: 2443
  obj_loader:
    data_root: /mnt/c/Users/xuehan/Data/CLOTH3D/train
    sub_category_json_path: /mnt/c/Users/xuehan/Data/CLOTH3D/train_meta/Tshirt_sub_categories_v3.json
    meta_json_path: /mnt/c/Users/xuehan/Data/CLOTH3D/train_meta/Tshirt_meta.json
    category: Tshirt
    sub_categories: [2]  # long
    use_wsl: True
    seed: 225
    num_splits: 1
    instance_filter_file_path: /home/hanxue/data/UniFolding/VR_Imitation/vr_imitation_flattening-folding-long_v5_dataset/Tshirt/train_instances.txt
  strategy:
    shuffle_instances: True
    instance_num_per_episode_per_proc: 400
    trial_num_per_instance: 1
    step_num_per_trial: 5
    warmup_sample_num: 800
    use_online_dataset: True
    max_memory_size: 100
    start_episode: 0
    episode_num: 10
    num_processes: 1
    skip_data_collection_in_first_episode: False
    skip_all_data_collection: False
    skip_all_model_training: False
    random_exploration:
      enable: True
      random_explore_prob: 0.8  # the probability for random exploration during data collection
      random_explore_top_ratio: 0.7  # the top-k ratio in random exploration (only choose from the best points)
    random_fold_config:
      random_fold_data_ratio: 0.3
      best_action_ratio: 0.3
    barrier:
      enable: False  # Set to true will enable barrier to synchronize with other processes
  runtime_training_config_override:
    datamodule:
      h5_path: /home/hanxue/data/UniFolding/VR_Imitation/vr_imitation_flattening-folding-long_v5_dataset/Tshirt/data.h5
      batch_size: 16
      num_workers: 4
      depth_scale_range: [0.1, 1.0]
    runtime_datamodule:
      debug: False
      batch_size: 16
      num_workers: 4
      episode_range: [0, 10]
      weighted_sampler:
        enable: True
        mode: 'linear'
        min_weight: 0.05
        max_sample_num: 4000
      # data augmentation
      max_normal_rot_angle: 20
      max_fold_rot_angle: 20
      max_fling_rot_angle: 30
      # For ClothDynamics environment
      depth_scale_range: [0.5, 1.5]
      # database
      use_database: False
    trainer:
      max_epochs: 40
      gradient_clip_val: 0.5
      detect_anomaly: False
    model:
      virtual_reward_head_params:
        fuse_nn_channels: [524, 256, 128]
        canonicalization_nn_channels: [128, 128, 1]
        alignment_nn_channels: [128, 128, 1]
        use_dense_feat: True
        use_nocs_dense_feat: True
        use_dynamic_deformable_weight: False
        xyz_distance_weight_alpha: 50.0
        deformable_weight: 0.7
      cos_t_max: 40
      loss_cls_weight: 0.01
      loss_grasp_weight: 10.0
      loss_nocs_weight: 10.0
      loss_offset_weight: 1.0
      loss_canonicalization_reward_weight: 20.0
      loss_alignment_reward_weight: 4.0
      virtual_loss_weight_factor: 5.0
    logger:
      experiment_name: Tshirt-long-action14-dataset-v5_hybrid
  reward:
    deformable_weight: 0.7

inference:
  args:
    only_smoothing: true  # set to true will only execute fling and pick_and_place action
    action_type_override:  # override action type in inference
      enable: true  # false by default
      type: fling

logging:
  tag: "debug"
  note: hybrid-data
  path: "/home/hanxue/data/UniFolding/log"
